"""Data-provider contract for TBMCP.

The AI tools (`mcp.server`) and the web API (`api.app`) depend ONLY on the
`DataProvider` contract below - never on a concrete broker. Today the only
implementation is `UpstoxClient` (Upstox v2). To add a future broker (or if
Upstox changes its policy), write a class that satisfies this Protocol and
register it in `providers.create_provider`. Nothing else in the app changes,
and the AI's tool names stay identical.
"""
from __future__ import annotations

from typing import Optional, Protocol

from models import (
    Candle,
    FuturesChain,
    Instrument,
    Margin,
    MarketDepth,
    MarketHoliday,
    MarketStatus,
    OptionChain,
)


class DataProvider(Protocol):
    """The single contract every data source must satisfy."""

    def get_option_chain(self, symbol: str, expiry_date: Optional[str] = None) -> OptionChain: ...
    def get_expiry_dates(self, symbol: str) -> list[str]: ...
    def get_spot_price(self, symbol: str) -> float: ...
    def get_full_quote(self, symbol: str) -> dict[str, float]: ...
    def get_full_quotes(self, symbols: list[str]) -> dict[str, dict]: ...
    def get_historical_data(self, symbol: str, interval: str = "day", days: int = 60) -> list[Candle]: ...
    def get_futures_chain(self, symbol: str, expiry_date: Optional[str] = None) -> FuturesChain: ...
    def get_market_depth(self, symbol: str) -> MarketDepth: ...
    def get_margin(self, instruments: list[dict]) -> Margin: ...
    def get_pcr(self, symbol: str, expiry: str, date: str, bucket_interval: int = 60) -> object: ...
    def get_max_pain(self, symbol: str, expiry: str, date: str, bucket_interval: int = 60) -> object: ...
    def get_oi(self, symbol: str, expiry: str, date: str) -> object: ...
    def get_change_oi(self, symbol: str, expiry: str, date: str, interval: int = 1) -> object: ...
    def get_fii(self, data_type: str = "NSE_FO|INDEX_FUTURES", interval: str = "1D") -> object: ...
    def get_dii(self, data_type: str = "NSE_EQ|CASH", interval: str = "1D") -> object: ...
    def get_market_status(self, exchange: str = "NSE") -> MarketStatus: ...
    def get_market_holidays(self, date: Optional[str] = None) -> list[MarketHoliday]: ...
    def get_market_timings(self, date: str) -> object: ...
    def get_instruments(self, query: str, exchange: str = "NSE") -> list[Instrument]: ...
    def get_company_profile(self, isin: str) -> object: ...
    def get_share_holdings(self, isin: str) -> object: ...
    def get_key_ratios(self, isin: str) -> object: ...
    def get_corporate_actions(self, isin: str) -> object: ...
    def get_competitors(self, isin: str) -> object: ...
    def get_news(self, instrument_keys: list[str]) -> object: ...
    def build_login_url(self, api_key: str, redirect_uri: str, code_challenge: Optional[str] = None) -> str: ...
    def exchange_code_for_token(self, code: str, redirect_uri: str, code_verifier: Optional[str] = None) -> str: ...
