"""Pure HTML rendering for the option-chain table.

This module contains NO business logic and NO inline styles. Cells reference
CSS classes only; the colours come from two places: the static theme/layout in
`frontend/style.css` (gain/loss emphasis via `--success`/`--danger`/`--muted`),
and the per-tag buildup colours generated by `chain_css()` from `BUILDUP_COLORS`
in `constants`. The UI injects `chain_css()` once, then just calls
`render_chain`.
"""
from __future__ import annotations

from typing import Any, Optional

from analytics import buildup_color
from constants import BUILDUP_COLORS


def _fmt(value: Any, decimals: int = 2) -> str:
    """Format a number for display (null -> dash, ints ungrouped decimals)."""
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:,.{decimals}f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def _change_class(value: float) -> str:
    """CSS class for a signed number (gain / loss / flat)."""
    if value > 0:
        return "tbmcp-up"
    if value < 0:
        return "tbmcp-down"
    return "tbmcp-flat"


def _buildup_class(tag: str) -> str:
    """CSS class that carries a buildup tag's colour (defined in chain_css)."""
    slug = tag.strip().lower().replace(" ", "-")
    return f"tbmcp-build tbmcp-build-{slug}"


def _greek_cell(value: Any, decimals: int = 4) -> str:
    """Render a Greek value cell with semantic class."""
    return f"<td class='tbmcp-cell-greek'>{_fmt(value, decimals)}</td>"


def _iv_cell(value: Any) -> str:
    """Render IV cell with semantic class."""
    return f"<td class='tbmcp-cell-iv'>{_fmt(value, 2)}</td>"


def _pct_cell(value: Any) -> str:
    """Render percentage cell with semantic class and color."""
    cls = _change_class(value if isinstance(value, (int, float)) else 0)
    return f"<td class='tbmcp-cell-pct {cls}'>{_fmt(value, 2)}%</td>"


def _volume_cell(value: Any) -> str:
    """Render volume cell with semantic class."""
    return f"<td class='tbmcp-cell-volume'>{_fmt(value, 0)}</td>"


def _oi_cell(value: Any) -> str:
    """Render OI cell with semantic class."""
    return f"<td class='tbmcp-cell-oi'>{_fmt(value, 0)}</td>"


def _ltp_cell(value: Any) -> str:
    """Render LTP cell with semantic class."""
    return f"<td class='tbmcp-cell-ltp'>{_fmt(value, 2)}</td>"


def _bid_ask_cells(leg: dict) -> list[str]:
    """Return list of bid/ask cell strings."""
    return [
        f"<td class='tbmcp-cell-bid-ask'>{leg.get('bidQty', 0)}</td>",
        f"<td class='tbmcp-cell-bid-ask'>{_fmt(leg.get('bidPrice', 0), 2)}</td>",
        f"<td class='tbmcp-cell-bid-ask'>{_fmt(leg.get('askPrice', 0), 2)}</td>",
        f"<td class='tbmcp-cell-bid-ask'>{leg.get('askQty', 0)}</td>",
    ]


def _buildup_cell(tag: str) -> str:
    """Render buildup cell with semantic class."""
    return f"<td class='tbmcp-cell-buildup {_buildup_class(tag)}'>{tag}</td>"


def _leg_cells(leg: Optional[dict[str, Any]]) -> str:
    """CALLS side cells (Left → Center): Buildup, Greeks, IV, Vol%, Volume, OI, LTP%, LTP, Bid/Ask."""
    if not leg:
        return "<td class='tbmcp-empty'>-</td>" * 14
    
    cells = [
        _buildup_cell(leg['buildTag']),
        _greek_cell(leg.get('vega', 0)),
        _greek_cell(leg.get('theta', 0)),
        _greek_cell(leg.get('gamma', 0)),
        _greek_cell(leg.get('delta', 0)),
        _iv_cell(leg['impliedVolatility']),
        _pct_cell(leg.get('oiChangePct', 0)),
        _volume_cell(leg['totalTradedVolume']),
        _oi_cell(leg['openInterest']),
        _pct_cell(leg['pChange']),
        _ltp_cell(leg['lastPrice']),
    ]
    cells.extend(_bid_ask_cells(leg))
    return "".join(cells)


def _put_cells(leg: Optional[dict[str, Any]]) -> str:
    """PUTS side cells (Center → Right): Ask/Bid, LTP, LTP%, OI, Volume, Vol%, IV, Greeks, Buildup."""
    if not leg:
        return "<td class='tbmcp-empty'>-</td>" * 14
    
    cells = list(reversed(_bid_ask_cells(leg)))
    cells.extend([
        _ltp_cell(leg['lastPrice']),
        _pct_cell(leg['pChange']),
        _oi_cell(leg['openInterest']),
        _volume_cell(leg['totalTradedVolume']),
        _pct_cell(leg.get('oiChangePct', 0)),
        _iv_cell(leg['impliedVolatility']),
        _greek_cell(leg.get('delta', 0)),
        _greek_cell(leg.get('gamma', 0)),
        _greek_cell(leg.get('theta', 0)),
        _greek_cell(leg.get('vega', 0)),
    ])
    cells.append(_buildup_cell(leg['buildTag']))
    return "".join(cells)


def _buildup_css_rules() -> str:
    """One CSS rule per buildup tag, colour pulled from constants."""
    rules = []
    for tag, color in BUILDUP_COLORS.items():
        slug = tag.strip().lower().replace(" ", "-")
        rules.append(f".tbmcp-build-{slug} {{ background:{color}; color:#ffffff; }}")
    return "\n".join(rules)


def chain_css() -> str:
    """Dynamic, data-driven colour rules for the buildup tags only.

    The buildup tag set (and its colours) lives in `constants.BUILDUP_COLORS`,
    so it must be generated at runtime. Gain/loss emphasis and the rest of the
    look (layout, spacing, dark theme, sticky header, pills) live in
    `frontend/style.css`.
    """
    return _buildup_css_rules()


def render_chain(chain: dict[str, Any]) -> str:
    """Render the full symmetrical option-chain table as HTML."""
    rows = chain.get("rows", [])
    if not rows:
        return '''<div class="tbmcp-empty-state">
            <div class="icon">📊</div>
            <h3>No Data Available</h3>
            <p>Select a symbol and expiry to view the option chain</p>
        </div>'''

    rows_html: list[str] = []
    for row in rows:
        strike = row.get("strikePrice", 0)
        ce = row.get("CE")
        pe = row.get("PE")
        
        # Calculate PCR for this strike
        ce_oi = ce.get("openInterest", 0) if ce else 0
        pe_oi = pe.get("openInterest", 0) if pe else 0
        pcr = (pe_oi / ce_oi) if ce_oi else 0
        
        rows_html.append(
            "<tr>"
            + _leg_cells(ce)
            + f"<td class='tbmcp-cell-strike'>{_fmt(strike, 0)}</td>"
            + f"<td class='tbmcp-cell-pcr'>{_fmt(pcr, 2)}</td>"
            + _put_cells(pe)
            + "</tr>"
        )
    
    # Symmetrical header: CALLS (14 cols) | Strike | PCR | PUTS (14 cols)
    header = (
        "<tr class='tbmcp-th'>"
        # CALLS side (Left → Center)
        "<th class='tbmcp-cell-buildup'>Buildup</th>"
        "<th class='tbmcp-cell-greek'>Vega</th>"
        "<th class='tbmcp-cell-greek'>Theta</th>"
        "<th class='tbmcp-cell-greek'>Gamma</th>"
        "<th class='tbmcp-cell-greek'>Delta</th>"
        "<th class='tbmcp-cell-iv'>IV</th>"
        "<th class='tbmcp-cell-pct'>Vol%</th>"
        "<th class='tbmcp-cell-volume'>Volume</th>"
        "<th class='tbmcp-cell-oi'>OI</th>"
        "<th class='tbmcp-cell-pct'>LTP%</th>"
        "<th class='tbmcp-cell-ltp'>LTP</th>"
        "<th class='tbmcp-cell-bid-ask'>BidQty</th>"
        "<th class='tbmcp-cell-bid-ask'>BidPrice</th>"
        "<th class='tbmcp-cell-bid-ask'>AskPrice</th>"
        "<th class='tbmcp-cell-bid-ask'>AskQty</th>"
        # Center columns
        "<th class='tbmcp-cell-strike'>Strike</th>"
        "<th class='tbmcp-cell-pcr'>PCR</th>"
        # PUTS side (Center → Right)
        "<th class='tbmcp-cell-bid-ask'>AskQty</th>"
        "<th class='tbmcp-cell-bid-ask'>AskPrice</th>"
        "<th class='tbmcp-cell-bid-ask'>BidPrice</th>"
        "<th class='tbmcp-cell-bid-ask'>BidQty</th>"
        "<th class='tbmcp-cell-ltp'>LTP</th>"
        "<th class='tbmcp-cell-pct'>LTP%</th>"
        "<th class='tbmcp-cell-oi'>OI</th>"
        "<th class='tbmcp-cell-volume'>Volume</th>"
        "<th class='tbmcp-cell-pct'>Vol%</th>"
        "<th class='tbmcp-cell-iv'>IV</th>"
        "<th class='tbmcp-cell-greek'>Delta</th>"
        "<th class='tbmcp-cell-greek'>Gamma</th>"
        "<th class='tbmcp-cell-greek'>Theta</th>"
        "<th class='tbmcp-cell-greek'>Vega</th>"
        "<th class='tbmcp-cell-buildup'>Buildup</th>"
        "</tr>"
    )
    
    return (
        "<div class='tbmcp-table-wrapper'>"
        + "<div class='tbmcp-card'>"
        + "<table class='tbmcp-table tbmcp-symmetrical'>"
        + f"<thead>{header}</thead>"
        + f"<tbody>{''.join(rows_html)}</tbody>"
        + "</table>"
        + "</div>"
        + "</div>"
    )
